### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by jesper7** [iterative/helm-charts#12]
We should have a changelog for our Helm charts so that users can read about breaking changes and adjust their `values.yml` accordingly.

**Comment by mjasion** [comment]
To not forget, maybe we can also do here:
- Automatic version bumping with changelog generation (I presented [semantic-release](https://github.com/semantic-release/semantic-release) + [helm-plugin](https://www.npmjs.com/package/semantic-release-helm))

@jesper7 maybe we need to move it to new task.
