### ISSUE TITLE
CSS breaks while using path based routing

### ISSUE THREAD

**Issue by rishdasubs** [iterative/helm-charts#85]
CSS break when hosting studio on non-default path, for instance `/studio` Screenshot attached

![image](https://user-images.githubusercontent.com/128061134/225648550-88e453e6-5ab0-496f-815a-dd8de2170a60.png)

**Comment by jesper7** [comment]
Hey Rishabh

This is fixed in Studio version v2.19.0 and onwards :slightly_smiling_face:
